services:
  - type: worker
    name: personal-points-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: "8083257429:AAEbtz5zQIifEkJhdVyvkbKy2IwCqh1PQMs"
      - key: PYTHON_VERSION
        value: "3.11.9"